---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
        - image: docker.io/trada98/spring-boot
          name: spring-boot
          resources: {}
          ports:
            - name: httpport
              containerPort: 8081
          volumeMounts:
            - name: spring-volume
              mountPath: /home/log
            - name: pv-storage
              mountPath: /home/log
      volumes:
        - name: spring-volume #volume
          hostPath:
            path: /data/spring
        - name: pv-storage
          persistentVolumeClaim:
            claimName: my-pvc #metadataname in script/spring-pv.yaml
status: {}
