---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
        - image: docker.io/trada98/spring-boot
          name: spring-boot
          resources: {}
          ports:
            - name: httpport
              containerPort: 8081
          volumeMounts:
            - name: spring-volume
              mountPath: /spring-boot/log
      volumes:
        - name: spring-volume
          hostPath:
            path: /data/spring
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  ports:
    - name: httpport
      port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30083
  selector:
    app: demo
  type: NodePort
status:
  loadBalancer: {}
