server:
  port: 8081
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: 172.17.0.5
      port: 8002
      password: Khiet@123
      username: default
  application:
    name: sample
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://172.17.0.4:3306/lab
    username: khiet
    password: Khiet@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level: 
      org.springframework: WARN
      org.hibernate: WARN
