apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: localdisk #refencing to class name localdisk in storageclass.yaml
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
